@startuml
skinparam classbackgroundcolor #ffffff
skinparam classdiamondbackgroundcolor #ffffff
skinparam classdiamondbordercolor #000000
skinparam classbordercolor #000000
skinparam classfontsize 18
skinparam classfontname "Liberation Mono"
skinparam classattributefontsize 18
skinparam classattributefontname "Liberation Mono"
skinparam classAttributeIconSize 0
hide circle
class Course {
  
  - name: String
  - day: int
  - startTime: int
  - endTime: int
  
  + Course(name: String, day: int, startTime: int, endTime:int)
  
  + getName(): String
  
  + getDay(): int
  + setDay(day: int): void
  
  + getStartTime(): int
  + setStartTime(startTime: int): void
  
  + getEndTime(): int
  + setEndTime(endTime: int): void
  
  + toString(): String
  + compareTo(other: Course): int
}
@enduml
